from enum import Enum, auto

class SYMBOL_CODES(Enum):
    UNDEFINED = 0
    SHEET_BORDER = 1
    NORMAL_SYMBOL = 2
    SIGNAL_CARRYING = 3
    REFERENCE_SYMBOLS = 4
    CONNECTOR_DOCUMENTATION_SYMBOL = 6
    BLOCK_SYMBOL = 8
    CONNECTOR_ON_BLOCK_BOUNDARY = 9
    FREE_CONNECTOR_SYMBOLS = 10
    FIELD_SYMBOL = 13
    DYNAMIC_SYMBOL = 14
    ASIC_SYMBOL = 15
    FORMBOARD_TABLE_SYMBOL = 16
    CONTACT_ARRANGEMENT_SYMBOL = 17
    HIERARCHICAL_BLOCK_SYMBOL = 38
    PORT_ON_HIERARCHICAL_BLOCK = 39
    PORT_ON_HIERARCHICAL_SHEET = 40
    TERMINAL_ROW_SYMBOL = 50
    MOUNT_SYMBOL = 60
    PANEL_SYMBOL = 61
    CABLE_DUCT_SYMBOL = 62
    TEMPLATE_SYMBOL_FOR_PINS = 100
    TEMPLATE_SYMBOL_FOR_TEXTS = 101
    ATTRIBUTE_TEMPLATE_SYMBOL = 102
    PIN_TEMPLATE_SYMBOL = 103
    PAD_TEMPLATE_SYMBOL = 104

class SYMBOL_STATE(Enum):
    AVAILABLE = 0
    IS_MISSING = 1
    AUTO_GENERATED = 2

